apiVersion: v1
kind: ConfigMap
metadata:
  name: database-sql
  namespace: tech-challenge
data:
  init-db1.sql: |
    do $$
    begin
        if not exists (
    select
      1
    from
      pg_namespace
    where
      nspname = 'fast_food') then
            create schema fast_food;
    end if;
    end
    $$;

    create type fast_food.payment_type_enum as enum (
      'DINHEIRO',
      'CARTAO_CREDITO',
      'CARTAO_DEBITO',
      'PIX',
      'VALE_REFEICAO'
    );

    create type fast_food.payment_status_enum as enum (
      'PENDENTE',
      'AUTORIZADO',
      'REJEITADO',
      'REEMBOLSADO'
    );

    create table if not exists fast_food.payment(
        id uuid,
        effective_date timestamp default current_timestamp,
        type fast_food.payment_type_enum not null,
        status fast_food.payment_status_enum not null default 'PENDENTE',
        updated_at timestamp default current_timestamp,
        external_id varchar,
        constraint pk_payment primary key (id)
    );
