apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-postgres
  namespace: tech-challenge
  labels:
    app: tech-challenge-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: tech-challenge-postgres
