apiVersion: v1
kind: ConfigMap
metadata:
  name: ${REPO_NAME}-secret
  namespace: default
  labels:
    app: ${REPO_NAME}
data:
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: "${DATABASE_PORT}"
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}
  MESSAGE_BROKER_ORDER_QUEUE: ${MESSAGE_BROKER_ORDER_QUEUE}
  MESSAGE_BROKER_PAYMENT_QUEUE: ${MESSAGE_BROKER_PAYMENT_QUEUE}
  MESSAGE_BROKER_URL: ${MESSAGE_BROKER_URL}
  MERCADO_PAGO_BASE_URL: ${MERCADO_PAGO_BASE_URL}
  MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
  LISTEN_ORDER_PAYMENT_URL: ${LISTEN_ORDER_PAYMENT_URL}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${REPO_NAME}
  template:
    metadata:
      labels:
        app: ${REPO_NAME}
    spec:
      containers:
      - name: ${REPO_NAME}
        image: ${ECR_REGISTRY}/${REPO_NAME}:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: ${REPO_NAME}-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
